// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PAA_Modul7.Data;

#nullable disable

namespace PAA_Modul7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527154307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PAA_Modul7.Models.MahasiswaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("MataKuliah")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramStudi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAkademik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Mahasiswas");
                });

            modelBuilder.Entity("PAA_Modul7.Models.PembayaranEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("JumlahBayar")
                        .HasColumnType("numeric");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MahasiswaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusPembayaran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TagihanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalPembayaran")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TagihanId");

                    b.ToTable("Pembayarans");
                });

            modelBuilder.Entity("PAA_Modul7.Models.TagihanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JatuhTempo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MahasiswaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NilaiUkt")
                        .HasColumnType("numeric");

                    b.Property<string>("ProgramStudi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusTagihan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TahunAkademik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalDibayar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tagihans");
                });

            modelBuilder.Entity("PAA_Modul7.Models.PembayaranEntity", b =>
                {
                    b.HasOne("PAA_Modul7.Models.TagihanEntity", "Tagihan")
                        .WithMany()
                        .HasForeignKey("TagihanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tagihan");
                });
#pragma warning restore 612, 618
        }
    }
}
